# Generated by Django 2.2.4 on 2019-08-05 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlots',
            fields=[
                ('number_of_class', models.IntegerField(primary_key=True, serialize=False)),
                ('time_slot_begin', models.TimeField(verbose_name='time of beginning')),
                ('time_slot_end', models.TimeField(verbose_name='time of ending')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(default=0)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_handler.Building')),
            ],
        ),
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200)),
                ('number_of_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='df_handler.TimeSlots')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='df_handler.Room')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='df_handler.Teacher')),
            ],
        ),
    ]
