# Generated by Django 2.2.4 on 2019-08-07 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_handler', '0002_auto_20190807_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='classname',
            name='day',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='df_handler.DayOfWeek'),
        ),
    ]
